<?php

namespace MovehqApp\Http\Controllers;

class HomeController extends Controller
{
    public function home()
    {
        // Show the index.html file generated by webpack
        return response('nothing to see');
    }
}
